// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ryhnsbyuenothrmchyws.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ5aG5zYnl1ZW5vdGhybWNoeXdzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1Mjg0NzgsImV4cCI6MjA2NjEwNDQ3OH0.EZPCeGDnAAUvRvp-_yYQNqZYr5VMR6mPfpi54ap_GSU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);